### ISSUE TITLE
Shapfile subsetting via Harmony is broken

### ISSUE THREAD

**Issue by frankinspace** [podaac/l2ss-py#125]
Trying to run the shapefile subsetting tutorial notebook https://github.com/podaac/tutorials/blob/master/notebooks/harmony%20subsetting/shapefile_subset.ipynb

Results in a Harmony error "Service request failed with unknown error." 

Investigating the logs for the request in question found this:

```
{"app_message": "Calling l2ss-py subset with params {'shapefile_path': '/tmp/tmptwlzxtcz/f21a94f3df9f4cf58238dfc86b950b441ca7b0563ce717d3003bbb0bd0b4bfb2.geojson', 'bbox': array([[-180,  180],\n       [ -90,   90]]), 'output_file': '/home/dockeruser/data/e1a415d327b7306c251be4529de82605df8a39ec07dd0dff2ea5c394ae066417.nc', 'file_to_subset': '/tmp/tmptwlzxtcz/e1a415d327b7306c251be4529de82605df8a39ec07dd0dff2ea5c394ae066417.nc', 'origin_source': 'https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/ASCATB-L2-Coastal/ascat_20220330_152100_metopb_49454_eps_o_coa_3202_ovw.l2.nc'}", "user": "nickles", "requestId": "3cbd5443-390f-499b-9fe4-233c590df8eb", "timestamp": "2022-10-25T18:32:46.468268Z", "level": "INFO", "application": "/home/dockeruser/.local/bin/l2ss_harmony"}
ERROR:root:subset() got an unexpected keyword argument 'shapefile_path'
Traceback (most recent call last):
  File "/home/dockeruser/.local/lib/python3.9/site-packages/harmony/cli.py", line 215, in _invoke
    (out_app_message, out_catalog) = adapter.invoke()
  File "/home/dockeruser/.local/lib/python3.9/site-packages/harmony/adapter.py", line 116, in invoke
    return (self.app_message, self._process_catalog_recursive(self.catalog))
  File "/home/dockeruser/.local/lib/python3.9/site-packages/harmony/adapter.py", line 181, in _process_catalog_recursive
    output_item = self.process_item(item.clone(), source)
  File "/worker/podaac/subsetter/subset_harmony.py", line 170, in process_item
    result_bbox = subset.subset(**subset_params)
TypeError: subset() got an unexpected keyword argument 'shapefile_path'
```

**Comment by GodwinShen** [comment]
This was probably fixed in other tickets, should re-run the notebook to confirm.

**Comment by GodwinShen** [comment]
The granules listed in the current version of the notebook in cell 14 cannot be found when making the harmony_client.submit call. By updating the granules to G2081656126-POCLOUD, G2081939831-POCLOUD and G2081745076-POCLOUD, the notebook runs just fine.  I'll create a branch to fix the granule IDs in cell 14 so that the notebook will run end-to-end.

**Comment by GodwinShen** [comment]
Closing this ticket since this is no longer an issue with l2ss-py.  The shapefile subsetting notebook is broken though, that will be tracked in another ticket https://github.com/podaac/tutorials/issues/274.
