### ISSUE TITLE
SWOT collections failing temporal subsetting

### ISSUE THREAD

**Issue by jamesfwood** [podaac/l2ss-py#189]
The SWOT collections are failing temporal subsetting. 

This simulated harmony request works, but the real collections fail.

Simulated (Working):
https://harmony.earthdata.nasa.gov/C2152044763-POCLOUD/ogc-api-coverages/1.0.0/collections/ssh_karin%2Cssha_karin%2Cssh_karin_2%2Cssha_karin_2%2Ctime%2Ctime_tai%2Clongitude%2Clatitude/coverage/rangeset?subset=lon(-125.57812%3A-124.73438)&subset=lat(34.84931%3A35.83342)&subset=time(%222012-01-01T00%3A00%3A00Z%22%3A%222012-03-31T23%3A59%3A59Z%22)&format=application%2Fnetcdf

Make the real collections work also.

**Comment by sliu008** [comment]
https://github.com/podaac/l2ss-py/pull/190

**Comment by jamesfwood** [comment]
Test in Data Subscriber when ready.

**Comment by jamesfwood** [comment]
@davidcolemanjpl l2ss-py was updated in harmony in UAT only.  Please try to test this in UAT only.  You may need help from @jjmcnelis to setup the test case.  Thanks!

**Comment by davidcolemanjpl** [comment]
@jamesfwood I'l review, but will need more details regarding this validation:

E.g.
Acceptance criteria / inputs / Expected results

Version(s) under test  (l2ss-py)



Related ticket PODAAC-5476

**Comment by jamesfwood** [comment]
@davidcolemanjpl you can also test this using the harmony call directly:

https://harmony.uat.earthdata.nasa.gov/C1256507988-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time("2023-04-18T18:00:00%2B00:00":"2023-04-20T07:00:00%2B00:00")&skipPreview=true

Something like this, but update the subset lon and lat and tweak the time a bit.

**Comment by jamesfwood** [comment]
@davidcolemanjpl here's another one that should work.  Just tweak the times.

https://harmony.uat.earthdata.nasa.gov/C1256507988-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=time("2023-04-19T02:00:00%2B00:00":"2023-04-19T04:00:00%2B00:00")&skipPreview=true

Hopefully you can test this soon so we can do a release this week.  Thanks!

**Comment by davidcolemanjpl** [comment]
**l2ss-py:2.6.0rc14; podaac-data-subscriber v1.15.0a3**

@jamesfwood
Thanks, ...the harmony jobID seems to trigger as expected when using call for the SWOT_L2_LR_SSH_BASIC_1.0 collection.

Are there example, valid harmony calls for exercising other SWOT sub-collections under test?:
SWOT_L2_LR_SSH_EXPERT_1.0
SWOT_L2_LR_SSH_UNSMOOTHED_1.0
SWOT_L2_LR_SSH_WINDWAVE_1.0
SWOT_L2_NALT_IGDR_SSHA_1.0
SWOT_L2_NALT_OGDR_SSHA_1.0

**_note_**: When attempting to execute a harmony call directly using the **SWOT_L2_LR_SSH_EXPERT_1.0** collection (C1256122852-POCLOUD), the jobID hung at the running status
See jobID : efe48442-72ee-454f-8e13-93c3202a726e  

See jobID: 6d36b26c-be0e-4423-840c-a005fa0dc903. - FAILED
_WorkItem failed: podaac/l2ss-py:2.6.0rc14: Service request failed with an unknown error_

[https://harmony.uat.earthdata.nasa.gov/C1256122852-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time("2023-04-17T18:00:00%2B00:00":"2023-04-19T07:00:00%2B00:00")&skipPreview=true](https://harmony.uat.earthdata.nasa.gov/C1256122852-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time(%222023-04-17T18:00:00%2B00:00%22:%222023-04-19T07:00:00%2B00:00%22)&skipPreview=true)

See jobID: 02e0e68f-bf23-4960-b0e0-4ce0687672da
"The job failed with 2 errors. See the errors field for more details"

**_note2_**: The L2SS-Py functionality seems to work okay when sub-setting SWOT_L2_LR_SSH_EXPERT_1.0 collection nominally (via HiTIDE) : 
Can see the successful jobID 14682326-2b58-4b85-9d1e-097c3a928653
https://harmony.uat.earthdata.nasa.gov/jobs/14682326-2b58-4b85-9d1e-097c3a928653




**podaac-data-subscriber v1.15.0a3:** - anomaly 
_SWOT_L2_LR_SSH_BASIC_1.0_

 % podaac-data-downloader -c SWOT_L2_LR_SSH_BASIC_1.0  -d ./data --start-date 2023-04-17T18:00:00Z --end-date 2023-04-21T07:00:00Z --subset -b="-125.57812,34.84931,-124.73438,35.83342"
[2023-10-04 12:55:57,631] {podaac_data_downloader.py:382} ERROR - Uncaught exception occurred during execution.
Traceback (most recent call last):
  File "/Users/colemand/work/env/lib/python3.10/site-packages/subscriber/podaac_data_downloader.py", line 380, in main
    run()
  File "/Users/colemand/work/env/lib/python3.10/site-packages/subscriber/podaac_data_downloader.py", line 142, in run
    collection_id = pa.get_cmr_collection_id(
  File "/Users/colemand/work/env/lib/python3.10/site-packages/subscriber/podaac_access.py", line 574, in get_cmr_collection_id
    raise ValueError(f'No collections found in CMR for {collection_short_name}/{provider}')
ValueError: No collections found in CMR for SWOT_L2_LR_SSH_BASIC_1.0/POCLOUD

 (_I'll keep investigating this_)

**Comment by davidcolemanjpl** [comment]
**l2ss-py:2.6.0rc14; 
podaac-data-subscriber v1.15.0a3**

UAT

**SWOT_L2_LR_SSH_BASIC_1.0**:
Data subscriber issue: _ValueError: No collections found in CMR for C1256507988-POCLOUD/POCLOUD_


**SWOT_L2_LR_SSH_EXPERT_1.0**:
Data subscriber issue:  _ValueError: No collections found in CMR for SWOT_L2_LR_SSH_EXPERT_1.0/POCLOUD_

When using Harmony call directly, the subset failed for SWOT_L2_LR_SSH_EXPERT_1.0 (see Harmony  jobID: 178ea40f-643a-4d78-8ea3-c8e8c49ac038)
_"WorkItem failed: podaac/l2ss-py:2.6.0rc14: Service request failed with an unknown error"_


**SWOT_L2_LR_SSH_UNSMOOTHED_1.0**:
Data subscriber issue: _ValueError: No collections found in CMR for SWOT_L2_LR_SSH_UNSMOOTHED_1.0/POCLOUD_



**SWOT_L2_LR_SSH_WINDWAVE_1.0**:
Data subscriber issue: _ValueError: No collections found in CMR for SWOT_L2_LR_SSH_WINDWAVE_1.0/POCLOUD_

When using Harmony call Directly, the subset FAILED for SWOT_L2_LR_SSH_WINDWAVE_1.0
(see Failed jobID: c3b76190-f155-4f5e-aa8a-bc2d5da6270e)
_"WorkItem failed: podaac/l2ss-py:2.6.0rc14: Service request failed with an unknown error"_




**SWOT_L2_NALT_IGDR_SSHA_1.0**: 
l2ss-py:2.6.0rc14 - OKAY - PASS
podaac-data-subscriber v1.15.0a3 - OKAY - PASS



**SWOT_L2_NALT_OGDR_SSHA_1.0**:
l2ss-py:2.6.0rc14 - OKAY - PASS
podaac-data-subscriber v1.15.0a3 - OKAY - PASS

**Comment by jamesfwood** [comment]
@davidcolemanjpl how do you run data subscriber with UAT sources?  collection ids, using uat services, etc.

**Comment by davidcolemanjpl** [comment]
Correct, utilized the respective Data Subscriber UAT Install Instructions

**Comment by jamesfwood** [comment]
@davidcolemanjpl We deployed a new l2ss-py to OPS.  Can you please test this again in OPS?

**Comment by jamesfwood** [comment]
Harmony may be down right now, so please test when it's back running again.
Test here:
https://harmony.earthdata.nasa.gov/workflow-ui

**Comment by davidcolemanjpl** [comment]
HITIDE UI **OPS** V4.16.1
L2SS-PY:v**2.6.0**


@jamesfwood 

Related SWOT L2 collections currently displaying in HiTIDE UI (OPS):
**SWOT_L2_NALT_IGDR_SSHA_1.0**   -- (C2628598397-POCLOUD) -- PASSED  

https://harmony.earthdata.nasa.gov/jobs/5945fd10-8785-4e56-9d7f-032beccc6623   (L2SS-py PASS via HiTIDE UI)
https://harmony.earthdata.nasa.gov/jobs/a6feb324-8b34-4900-b776-f7eebc1a0ae6    (L2SS-py PASS using Harmony call) 

**SWOT_L2_NALT_OGDR_SSHA_1.0** -- (C2628593693-POCLOUD)  -- PASSED  
https://harmony.earthdata.nasa.gov/jobs/5df9ba70-5243-456a-b7b2-d00a1ee5adcd    (L2SS-py PASS via HiTIDE UI)
https://harmony.earthdata.nasa.gov/jobs/413e36e1-fad7-493d-a7c6-7f988e8dbb3d  (L2SS-py  PASS using Harmony call)



_note_: the following  SWOT L2 LR collections have not  been implemented thus far in HiTIDE OPS UI  and/or EARTHDATASEARCH:
**SWOT_L2_LR_SSH_BASIC_1.0 
SWOT_L2_LR_SSH_EXPERT_1.0
SWOT_L2_LR_SSH_UNSMOOTHED_1.0 
SWOT_L2_LR_SSH_WINDWAVE_1.0**

**Comment by jamesfwood** [comment]
Hi @davidcolemanjpl can you please test this again?  Thanks!

**Comment by davidcolemanjpl** [comment]
NOTE: Testing scope for this ticket has been overcome by events,  SWOT_L2 v1.0 collections have been replaced  / updated to SWOT_L2 **v2.0**




HITIDE UI **OPS** v4.17.2
**L2SS-PY:v2.13.0**
CONCISE: v0.10.0
Harmony UI v1.0.18
Postman v11.15.0


NOTE: L2SS-py (and CONCISE) PASSed in HiTIDE UI for SWOT_L2 collections under test:
_**SWOT_L2_LR_SSH_Windwave_2.0
SWOT_L2_LR_SSH_Basic_2.0 
SWOT_L2_LR_SSH_EXPERT_2.0**_


 - SWOT_L2_LR_SSH_WINDWAVE_2.0: **PASS**
[https://harmony.earthdata.nasa.gov/](https://harmony.earthdata.nasa.gov/C2799465428-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time(%222012-03-01T18:00:00%2B00:00%22:%222023-04-21T07:00:00%2B00:00%22)&skipPreview=true&concatenate=true)C2799465507-POCLOUD[/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time("2024-11-20T18:00:00%2B00:00":"2024-11-25T07:00:00%2B00:00")&skipPreview=true&concatenate=true](https://harmony.earthdata.nasa.gov/C2799465428-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time(%222012-03-01T18:00:00%2B00:00%22:%222023-04-21T07:00:00%2B00:00%22)&skipPreview=true&concatenate=true)

Harmony Job status: https://harmony.earthdata.nasa.gov/jobs/02a13e84-8305-4358-ae3b-325fa1887a6b


- SWOT_L2_LR_SSH_BASIC_2.0: **PASS**
https://harmony.earthdata.nasa.gov/C2799465428-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time("2024-11-20T18:00:00%2B00:00":"2024-11-25T07:00:00%2B00:00")&skipPreview=true&concatenate=true

Harmony Job status: https://harmony.earthdata.nasa.gov/jobs/d80de02f-f433-4677-b8cf-bec5c30e76bb


- SWOT_L2_LR_SSH_EXPERT_2.0:  **PASS**
[https://harmony.earthdata.nasa.gov/](https://harmony.earthdata.nasa.gov/C2152044763-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time(%222012-03-01T18:00:00%2B00:00%22:%222023-04-21T07:00:00%2B00:00%22)&skipPreview=true)C2799465497[-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time("2024-11-20T18:00:00%2B00:00":"2024-11-25T07:00:00%2B00:00")&skipPreview=true](https://harmony.earthdata.nasa.gov/C2152044763-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931:35.83342)&subset=lon(-125.57812:-124.73438)&subset=time(%222012-03-01T18:00:00%2B00:00%22:%222023-04-21T07:00:00%2B00:00%22)&skipPreview=true)&concatenate=true

Harmony Job status: https://harmony.earthdata.nasa.gov/jobs/d72ad583-3c62-4ea2-8c4e-3faa2c98449e



**_podaac-data-subscriber:_**
- **SWOT_L2_LR_SSH_Windwave_1.0 / 2.0**: **OKAY / PASS**
(8 granules) - 1 granule INITIALLY failed L2SS-Py - (https://harmony.earthdata.nasa.gov/jobs/fb876d99-07f2-4e85-b494-9e0091024b7b) - Job _complete_with_errors_
`% podaac-data-subscriber -c SWOT_L2_LR_SSH_Windwave_2.0 -d ./data --start-date 2024-11-23T00:00:00Z --end-date 2024-11-25T00:00:00Z --subset -b="120,-30,160,20" (all L2SS-Py steps PASSED 2ND TIME RUNNING) `
(2 granules) - downloaded 
`podaac-data-downloader -c SWOT_L2_LR_SSH_Windwave_1.0 -d ./data --start-date 2023-06-23T00:00:00Z --end-date 2023-06-25T00:00:00Z --subset -b="120,-30,160,20"
`

- **SWOT_L2_LR_SSH_Basic_1.0 / 2.0**: **OKAY / PASS**
(8 granules) 
`podaac-data-subscriber -c SWOT_L2_LR_SSH_Basic_2.0 -d ./data --start-date 2024-11-23T00:00:00Z --end-date 2024-11-25T00:00:00Z --subset -b="120,-30,160,20"`
(2 granules) - downloaded
`podaac-data-downloader -c SWOT_L2_LR_SSH_Basic_1.0 -d ./data --start-date 2023-06-22T18:00:00Z --end-date 2023-06-23T07:00:00Z --subset -b="-125.57812,34.84931,-124.73438,35.83342"`


- **SWOT_L2_LR_SSH_Expert_1.0 / 2.0**: **OKAY / PASS**
(8 granules) 
`podaac-data-subscriber -c SWOT_L2_LR_SSH_Expert_2.0`
(2 granules) - downloaded
`podaac-data-downloader -c SWOT_L2_LR_SSH_Expert_1.0
`

**Comment by jamesfwood** [comment]
Awesome!  Thanks David!
