### ISSUE TITLE
Service request failed with an unknown error

### ISSUE THREAD

**Issue by frankinspace** [podaac/l2ss-py#54]
From @jjmcnelis 

I’m getting an error back from Harmony for my MODIS-A L2 SST subset requests: https://harmony.earthdata.nasa.gov/jobs/0ed1a0b0-6f2d-47cb-b286-c340c52297e0 I submitted identical requests several times last year between March and December, so I know this dataset and request to be valid/compatible with harmony. Also, I think this error/response message is the same as the one that Celia was receiving for the SWOT L2 SSH requests that we looked at together last week.

```
{
  "username": "jmcnelis",
  "status": "failed",
  "message": "WorkItem [44006] failed with error: ghcr.io/podaac/l2ss-py:1.3.0: Service request failed with an unknown error",
  "progress": 0,
  "createdAt": "2022-02-24T16:17:47.903Z",
  "updatedAt": "2022-02-24T16:18:04.155Z",
  "links": [
    {
      "href": "https://harmony.earthdata.nasa.gov/service-results/harmony-prod-staging/public/podaac/l2-subsetter/1da09702-4bdc-4475-8d6d-d68d6606fd2d/20190101031001-JPL-L2P_GHRSST-SSTskin-MODIS_A-N-v02.0-fv01.0_subsetted.nc4",
      "title": "20190101031001-JPL-L2P_GHRSST-SSTskin-MODIS_A-N-v02.0-fv01.0_subsetted.nc4",
      "type": "application/x-netcdf4",
      "rel": "data",
      "bbox": [
        -13.3,
        37.7,
        -12.8,
        38.5
      ],
      "temporal": {
        "start": "2019-01-01T03:10:01.000Z",
        "end": "2019-01-01T03:15:00.000Z"
      }
    },
    {
      "href": "https://harmony.earthdata.nasa.gov/jobs/0ed1a0b0-6f2d-47cb-b286-c340c52297e0?page=1&limit=2000",
      "title": "The current page",
      "type": "application/json",
      "rel": "self"
    }
  ],
  "request": "https://harmony.earthdata.nasa.gov/C1940473819-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?subset=lat(37.707%3A38.484)&subset=lon(-13.265%3A-12.812)&subset=time(%222019-01-01%22%3A%222019-01-31%22)",
  "numInputGranules": 103,
  "jobID": "0ed1a0b0-6f2d-47cb-b286-c340c52297e0"
}
```

**Comment by skorper** [comment]
I was able to find the stacktrace and recreate this error locally. Here's the stack trace:

```
[2022-02-24 16:56:35,867] {run_subsetter.py:87} INFO - Executing subset on /Users/skperez/Documents/PO.DAAC/data/MODIS_A-JPL-L2P-v2019.0/20190130221500-JPL-L2P_GHRSST-SSTskin-MODIS_A-N-v02.0-fv01.0.nc...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/skperez/Documents/PO.DAAC/cloud/l2ss-py/podaac/subsetter/run_subsetter.py", line 108, in main
    run_subsetter(sys.argv[1:])
  File "/Users/skperez/Documents/PO.DAAC/cloud/l2ss-py/podaac/subsetter/run_subsetter.py", line 88, in run_subsetter
    subset.subset(
  File "/Users/skperez/Documents/PO.DAAC/cloud/l2ss-py/podaac/subsetter/subset.py", line 1130, in subset
    dataset.load().to_netcdf(output_file, 'w', encoding=encoding)
  File "/Users/skperez/Library/Caches/pypoetry/virtualenvs/l2ss-py-BNI8R1-E-py3.8/lib/python3.8/site-packages/xarray/core/dataset.py", line 1902, in to_netcdf
    return to_netcdf(
  File "/Users/skperez/Library/Caches/pypoetry/virtualenvs/l2ss-py-BNI8R1-E-py3.8/lib/python3.8/site-packages/xarray/backends/api.py", line 1072, in to_netcdf
    dump_to_store(
  File "/Users/skperez/Library/Caches/pypoetry/virtualenvs/l2ss-py-BNI8R1-E-py3.8/lib/python3.8/site-packages/xarray/backends/api.py", line 1119, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/Users/skperez/Library/Caches/pypoetry/virtualenvs/l2ss-py-BNI8R1-E-py3.8/lib/python3.8/site-packages/xarray/backends/common.py", line 265, in store
    self.set_variables(
  File "/Users/skperez/Library/Caches/pypoetry/virtualenvs/l2ss-py-BNI8R1-E-py3.8/lib/python3.8/site-packages/xarray/backends/common.py", line 303, in set_variables
    target, source = self.prepare_variable(
  File "/Users/skperez/Library/Caches/pypoetry/virtualenvs/l2ss-py-BNI8R1-E-py3.8/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 478, in prepare_variable
    encoding = _extract_nc4_variable_encoding(
  File "/Users/skperez/Library/Caches/pypoetry/virtualenvs/l2ss-py-BNI8R1-E-py3.8/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 274, in _extract_nc4_variable_encoding
    raise ValueError(
ValueError: unexpected encoding parameters for 'netCDF4' backend: ['units']. Valid encodings are: {'fletcher32', 'contiguous', '_FillValue', 'zlib', 'dtype', 'least_significant_digit', 'chunksizes', 'shuffle', 'complevel'}
(base) 
```

It appears this appears on some, but not all, `MODIS_A-JPL-L2P-v2019.0` granules.
